// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "x2.h"

/////////////////////////////////////////////////////////////////////////////
// CX2

IMPLEMENT_DYNCREATE(CX2, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CX2 properties

/////////////////////////////////////////////////////////////////////////////
// CX2 operations
