// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "x3.h"

/////////////////////////////////////////////////////////////////////////////
// CX3

IMPLEMENT_DYNCREATE(CX3, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CX3 properties

/////////////////////////////////////////////////////////////////////////////
// CX3 operations
