function CMD = micro_stim(stim)
micro_globals;
%CMD = sprintf('$%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d',...
%              stim.stim,stim.index,stim.edge,stim.bitNo,stim.pos(1),...
%              stim.pos(2),stim.level,stim.start(1),stim.start(2),stim.stop(1),...
%              stim.stop(2),stim.delay,stim.width,stim.event);
switch (stim.stim)
    case stimBar
        CMD = sprintf('$%d;%d;%d;%d;%d;%d;%d;%d;%d',...
              stim.stim,stim.mode,stim.edge,stim.bitNo,...
              stim.start(1),stim.start(2),...
              stim.stop(1),stim.stop(2),...
              stim.event);
    case {stimRec, stimRew, stimLas}
        CMD = sprintf('$%d;%d;%d;%d;%d;%d;%d',...
              stim.stim,stim.bitNo,...
              stim.start(1),stim.start(2),...
              stim.stop(1),stim.stop(2),...
              stim.event);
    case {stimSky,stimLed}
        CMD = sprintf('$%d;%d;%d;%d;%d;%d;%d;%d;%d',...
              stim.stim,stim.pos(1),stim.pos(2),stim.level,...
              stim.start(1),stim.start(2),stim.stop(1),stim.stop(2),stim.event);
    case {stimSnd1,stimSnd2}
        CMD = sprintf('$%d;%d;%d;%d;%d;%d;%d',...
              stim.stim,stim.bitNo,stim.start(1),stim.start(2),...
              stim.stop(1),stim.stop(2),stim.event);
    case {stimFixWnd}
        CMD = sprintf('$%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d;%d',...
              stim.stim,stim.index,stim.pos(1),stim.pos(2),stim.width(1),stim.width(2),...
              stim.start(1),stim.start(2),stim.stop(1),stim.stop(2),stim.delay,stim.event);
    case {stimSpeed}
        CMD = sprintf('$%d;%d;%d;%d;%d;%d;%d;%d;%d;%d',...
              stim.stim,stim.mode,stim.pos(1),stim.pos(2),...
              stim.start(1),stim.start(2),stim.stop(1),stim.stop(2),stim.level,stim.event);
    otherwise
        CMD = '';
end
        
