// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "x5.h"

/////////////////////////////////////////////////////////////////////////////
// CX5

IMPLEMENT_DYNCREATE(CX5, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CX5 properties

/////////////////////////////////////////////////////////////////////////////
// CX5 operations
